version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1

    steps:
      - checkout
      - run:
          name: Installing Packages
          command: |
            sudo rm /etc/apt/sources.list
            echo "deb http://archive.debian.org/debian/ jessie-backports main" | sudo tee -a /etc/apt/sources.list
            echo "deb-src http://archive.debian.org/debian/ jessie-backports main" | sudo tee -a /etc/apt/sources.list
            echo "Acquire::Check-Valid-Until false;" | sudo tee -a /etc/apt/apt.conf.d/10-nocheckvalid
            echo 'Package: *\nPin: origin "archive.debian.org"\nPin-Priority: 500' | sudo tee -a /etc/apt/preferences.d/10-archive-pin
            sudo apt update
            sudo apt install wget zip unzip -y
      - run:
          name: Installing AWS CLI
          command: |
            sudo pip3 install awscli
      - run:
          name: Installing OpenJDK11
          command: |
            wget https://download.java.net/java/GA/jdk11/9/GPL/openjdk-11.0.2_linux-x64_bin.tar.gz
            tar xzvf openjdk-11.0.2_linux-x64_bin.tar.gz
            sudo mkdir /usr/lib/jvm
            sudo mv jdk-11.0.2 /usr/lib/jvm/openjdk-11.0.2/
            sudo update-alternatives --install /usr/bin/java java /usr/lib/jvm/openjdk-11.0.2/bin/java 1
            sudo update-alternatives --install /usr/bin/javac javac /usr/lib/jvm/openjdk-11.0.2/bin/javac 1
            java --version
            javac --version
            rm -rf openjdk-11.0.2_linux-x64_bin.tar.gz
      - run:
          name: Installing Maven 3.6
          command: |
            wget https://www-us.apache.org/dist/maven/maven-3/3.6.0/binaries/apache-maven-3.6.0-bin.tar.gz -P /tmp
            sudo tar xf /tmp/apache-maven-*.tar.gz -C /opt
            sudo ln -s /opt/apache-maven-3.6.0 /opt/maven
            sudo sh -c "echo $'export JAVA_HOME=/usr/lib/jvm/default-java
              export M2_HOME=/opt/maven
              export MAVEN_HOME=/opt/maven
              export PATH=${M2_HOME}/bin:${PATH}' > /etc/profile.d/maven.sh"
            sudo chmod +x /etc/profile.d/maven.sh
            source /etc/profile.d/maven.sh
            mvn -version  
      - run:
          name: Build Artifact
          command: |
            cd webapp
            ls -la
            mvn clean package
            sleep 5
            ls -la target
            cd
      - run:
          name: Zip Artifact
          command: |
            echo "Hello the current build number is ${CIRCLE_BUILD_NUM}"
            pwd
            ls -al
            mkdir -p codedeploy_artifact
            cp infrastructure/aws/codedeploy/*.sh .
            zip -r csye6225-web-app-${CIRCLE_BUILD_NUM}.zip webapp/build/libs/ROOT.war *.sh *.yml
            ls -al
            mv csye6225-web-app-${CIRCLE_BUILD_NUM}.zip codedeploy_artifact/
            ls -al
            pwd
            cd codedeploy_artifact
            ls -al
            pwd
            cd ..
            pwd
            ls -al
      - run:
          name: Upload Artifact to S3
          command: |
            cd codedeploy_artifact
            aws s3 cp csye6225-web-app-${CIRCLE_BUILD_NUM}.zip s3://${CODEDEPLOY_S3_BUCKET}   
      - run:
          name: Make CodeDeploy API call
          command: |
            echo "Hello CodeDeploy" 